name: 
author: 
url: 
baseurl: 
resume_site: 
description: 
github_username: 
github: 
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : 9a796fda0ca58a21a5a2
    clientSecret : f0391e335a825ee4894bb5e888268173bcfbe1c2
    repo : talks
    owner : GlovenIT
    admin : [GlovenIT]
